on:
  push:
    branches:
      health-check
  schedule:
    - cron: '15 * * * *'

jobs:
  health_check:

    runs-on: ubuntu-latest

    steps:
      - name: Perform health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-cicd-bloglist.onrender.com/health|http://full-stack-cicd-bloglist.onrender.com/health
          follow-redirect: false
          max-attempts: 2
          retry-delay: 5s
          retry-all: false


