name: CI/CD pipeline

on:
  push:
    branches:
      - cicd-pipeline
      - main
  pull_request:
    branches: main
    types: [opened, synchronize]

env:
  COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}
  SKIP_STRING: "#skip"
  EVENT_TYPE: ${{ github.event_name }}
  PRODUCTION_URL: ${{ vars.PRODUCTION_URL }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    outputs:
      skip_release: ${{ steps.deploy_status.outputs.skip_release }}

    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_DATABASE_CREDENTIALS }}
      PORT: ${{ secrets.TEST_DATABASE_PORT }}
      SECRET: ${{ secrets.TOKEN_SECRET }}

    if: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - id: deploy_status
        name: Check for skip tag in commit messages
        env:
          SKIP_TAG: ${{ contains(env.COMMIT_MESSAGES, env.SKIP_STRING) }}
        run: |
          echo "$SKIP_TAG"
          echo "joo"
          echo "skip_release=$SKIP_TAG" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          npm install
          cd frontend/ && npm install
          cd ../e2e-tests/ && npm install
          cd ..

      - name: Lint client
        run: npm run lint:ui

      - name: Lint server
        uses: creyD/prettier_action@v4.6
        with:
          dry: True
          no_commit: True
          clean_node_folder: False
          prettier_options: --check . --ignore-path ./.prettierignore --config ./.prettierrc
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build client
        run: npm run build:ui

      - name: Test client
        run: npm run test:ui

      - name: Test server
        run: npm test

      - name: Install end-to-end browsers
        run: |
          cd e2e-tests/
          npx playwright install --with-deps
      
      - name: Test end-to-end
        run: |
          npm run start:test & npm run test:e2e

      - name: Upload end-to-end testing report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30

  deploy_and_release:
    needs: [build_and_test]

    runs-on: ubuntu-latest

    if: ${{ (needs.build_and_test.outputs.skip_release == 'false') && (github.event_name == 'push') && (github.ref_name == 'main') }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy application to production
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: curl "$DEPLOY_HOOK"

      - name: Bump version tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        uses: anothrNick/github-tag-action@1.75.0

  notify_result:
    needs: [build_and_test, deploy_and_release]

    runs-on: ubuntu-latest

    env:
      BUILD_STATUS: ${{ needs.build_and_test.result }}
      DEPLOYMENT_STATUS: ${{ needs.deploy_and_release.result }}
      HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      HEAD_COMMIT_ID: ${{ github.event.head_commit.id }}
      HEAD_COMMIT_URL: ${{ github.event.head_commit.url }}


    if: ${{ always() }}

    steps:
      - name: Check env variables
        env:
          EVENT_AFTER_SHA: ${{ github.event.after }}
          EVENT_BEFORE_SHA: ${{ github.event.before }}
          EVENT_HEAD_COMMIT_ID: ${{ github.event.head_commit.id }}
          EVENT_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          EVENT_HEAD_COMMIT_URL: ${{ github.event.head_commit.url }}
          EVENT_PAYLOAD: ${{ github.event.payload }}

        run: |
          echo "$BUILD_STATUS"
          echo "$DEPLOYMENT_STATUS"
          echo "$EVENT_TYPE"
          echo "$EVENT_AFTER_SHA"
          echo "$EVENT_BEFORE_SHA"
          echo "$EVENT_HEAD_COMMIT_ID"
          echo "$EVENT_HEAD_COMMIT_MESSAGE"
          echo "$EVENT_HEAD_COMMIT_URL"
          echo "$EVENT_PAYLOAD"

      - name: Discord notification
        if: ${{ env.EVENT_TYPE == 'push' }}
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            DISCORD_EMBEDS: '[{
              "title": "Build report",
              "url": "${{ env.HEAD_COMMIT_URL }}",
              "author": {
                "name": "GitHub Actions",
                "url": "https://github.com/jukaveka/full-stack-cicd-bloglist/actions",
                "icon_url": "https://avatars.githubusercontent.com/u/44036562?s=200&v=4"
              },
              "fields": [
                {
                  "name": "Type",
                  "value": "${{ env.EVENT_TYPE }}"
                },
                {
                  "name": "Build status",
                  "value": "${{ env.BUILD_STATUS }}",
                  "inline": true
                },
                {
                  "name": "Deployment status",
                  "value": "${{ env.DEPLOYMENT_STATUS }}",
                  "inline": true
                }
              ]
              }]
              '
        uses: "Ilshidur/action-discord@ad5235de713df3ef38022185499b02ffe93b7efe"