name: CI/CD pipeline

on:
  push:
    branches:
      - cicd-pipeline

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install
          cd frontend/ && npm install
          cd ..

      - name: Lint client
        run: npm run lint:ui

      - name: Build client
        run: npm run build:ui

      - name: Test client
        run: npm run test:ui

      - name: Lint server
        uses: creyD/prettier_action@v4.6
        with:
          dry: True
          prettier_options: "--check --ignore-path .prettierignore --config .prettierrc"
          github_token: ${{ secrets.GITHUB_TOKEN }}